.PHONY: all
all: assign3

assign3: test_assign3_1.c dberror.c expr.c record_mgr.c rm_serializer.c storage_mgr.c buffer_mgr.c buffer_mgr_stat.c
    gcc -o assign3 test_assign3_1.c dberror.c expr.c record_mgr.c rm_serializer.c storage_mgr.c buffer_mgr.c buffer_mgr_stat.c


assign3_test_expr : test_expr.c dberror.c expr.c record_mgr.c rm_serializer.c storage_mgr.c buffer_mgr.c buffer_mgr_stat.c 
	gcc -o assign3 test_expr.c dberror.c expr.c record_mgr.c rm_serializer.c storage_mgr.c buffer_mgr.c buffer_mgr_stat.c 

.PHONY: clean
clean:
	rm assign3