CC = gcc
 
default: test1

test1: test_assign2_1.c storage_mgr.c dberror.c buffer_mgr.c buffer_mgr_stat.c
	$(CC) -o test1 test_assign2_1.c storage_mgr.c dberror.c buffer_mgr.c buffer_mgr_stat.c

test2: test_assign2_2.c storage_mgr.c dberror.c buffer_mgr.c buffer_mgr_stat.c
	$(CC) -o test2 test_assign2_2.c storage_mgr.c dberror.c buffer_mgr.c buffer_mgr_stat.c

run_test1:
	./test1

run_test2:
	./test2